### ISSUE TITLE
at_can_equip_artifact_trigger 

### ISSUE THREAD

**Issue by ProZeratul** [pharaox/artifact_trade#1]
Hello, I saw your message on steam I'm Kazarion from the Unofficial Patch, how did you find the built-in code for the original function ? I search in the game files but did not found anything.

**Comment by pharaox** [comment]
Hi Kazarion, nice to hear from you!

This is not the original function. I just came up with my own solution by looking at `can_equip` sections of all artifact templates. I noticed that for all such templates, `can_equip` is either empty or the same as `can_benefit`, except for `child_toy_template` and `adults_only_template`. Since `can_equip_artifact` is mostly used together with `can_benefit_from_artifact` (in my mod, and in the vanilla files as well), I decided to only address the 2 templates where they are different, otherwise pretend the artifact is always equippable. For the 2 templates, I found all places in the code where they were used and saw that I could check some variables / modifiers to determine if one of them was used during artifact creation (unfortunately, I think there is no better way to check this directly).

Like I said, not perfect, but better than the vanilla trigger that seems now to always return false if the character doesn't own the artifact.
